### ISSUE TITLE
ignore this message

### ISSUE THREAD

**Issue by NatC02** [mojotx/CharVomit#2]
This domain is not for sale, unless you're willing to pay an insane amount of money. Let's not get our bunches mixed with our oats, you can't afford it. Don't even bother trying to negotiate, I'll not lower the price. Not even if you offer me a Mercedes Benz, BMW or Lamborghini. Actually, if you offer me an oil field, then maybe we can negotiate. Or if you want to trade a nuclear weapon, that will work too. Just don't offer me anything less than that.

If you're still reading this, then I'm assuming that you really want to buy it, but don't have the money. Well, you could always try to win it in the lottery. I suggest playing on Thursday, because on Saturday there's usually no one playing. You can buy 5 tickets for only $7, why not give it a try?

Or if you do have the money, don't pay the lottery, pay me instead. Better yet, just give me the money and I'll pay the lottery myself. I'm not greedy, I just wanted to put this option out there. 

Let's just say the good 'ol Ferrari is not going to cut it this time. 

Here's a picture of an oil field. Keep in mind that if you offer me this, then we'll definitely negotiate.

![image](https://user-images.githubusercontent.com/45525285/137443332-017f9d92-b69f-4b07-ad27-3eda020405c0.png)

**Comment by mojotx** [comment]
This issue is not relevant to this open-source software project. 

The issue is a passive-aggressive parody, mocking the fact that my jarvis.com domain name is not for sale. I registered the domain in January 1995, because it's my surname. Value is subjective, and the domain is essentially priceless to me, and that's my right. 

If you dislike that fact, that's okay, but leaving these sorts of issues is not appropriate.
